In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import lenstronomy.Util.param_util as param

In [2]:
data = pd.read_csv('theta_file.csv')
data = data.head(10000)
data

      THETA_J2000  SOF_CM_G_1  SOF_CM_G_2
0       74.975723    0.172849   -0.162545
1       87.679436    0.083736    0.018023
2       79.053268   -0.004013   -0.059633
3      -74.631142    0.073121    0.049231
4       86.594742    0.020245   -0.022631
...           ...         ...         ...
9995   -25.314857   -0.269162    0.089892
9996     5.413002   -0.125716    0.018208
9997    54.291897    0.194503   -0.329392
9998    46.615898    0.000403   -0.055832
9999   -44.581551   -0.238290    0.130221

[10000 rows x 3 columns]

In [3]:
data['my_g2'] = data['SOF_CM_G_1'] * np.tan(2*np.radians(data['THETA_J2000']))
data['my_angle'] = np.degrees(np.arctan(data['SOF_CM_G_2']/data['SOF_CM_G_1'])/2)
data['my_ratio'] = (np.cos(2*np.radians(data['THETA_J2000'])) - data['SOF_CM_G_1']) / (np.cos(2*np.radians(data['THETA_J2000'])) + data['SOF_CM_G_1'])
data

      THETA_J2000  SOF_CM_G_1  SOF_CM_G_2      my_g2   my_angle  my_ratio
0       74.975723    0.172849   -0.162545  -0.099990 -21.620233  1.499019
1       87.679436    0.083736    0.018023  -0.006798   6.073486  1.183433
2       79.053268   -0.004013   -0.059633   0.001613  43.074940  0.991387
3      -74.631142    0.073121    0.049231   0.043481  16.976028  1.185964
4       86.594742    0.020245   -0.022631  -0.002418 -24.092713  1.041627
...           ...         ...         ...        ...        ...       ...
9995   -25.314857   -0.269162    0.089892   0.328029  -9.233893  2.474179
9996     5.413002   -0.125716    0.018208  -0.024041  -4.120569  1.293563
9997    54.291897    0.194503   -0.329392  -0.578496 -29.719237  4.132404
9998    46.615898    0.000403   -0.055832  -0.007134 -44.793303  1.014394
9999   -44.581551   -0.238290    0.130221  16.312635 -14.327910 -1.130596

[10000 rows x 6 columns]

In [4]:
lens_g2, lens_ratio, lens_angle = [], [], []
for index, row in data.iterrows():
    angle, ratio = param.ellipticity2phi_q(row['SOF_CM_G_1'], row['SOF_CM_G_2']) 
    g2 = (1-ratio)/(1+ratio)* np.sin(2*angle)
    lens_g2.append(g2)
    lens_ratio.append(ratio)
    lens_angle.append(np.degrees(angle))
data['lens_g2'] = lens_g2
data['lens_ratio'] = lens_ratio
data['lens_angle'] = lens_angle
#data['lens_angle_90'] = 90 + data['lens_angle']

In [5]:
data

,THETA_J2000,SOF_CM_G_1,SOF_CM_G_2,my_g2,my_angle,my_ratio,lens_g2,lens_ratio,lens_angle
0,74.975723,0.172849,-0.162545,-0.099990,-21.620233,1.499019,-0.162545,0.616460,-21.620233
1,87.679436,0.083736,0.018023,-0.006798,6.073486,1.183433,0.018023,0.842209,6.073486
2,79.053268,-0.004013,-0.059633,0.001613,43.074940,0.991387,-0.059633,0.887206,-46.925060
3,-74.631142,0.073121,0.049231,0.043481,16.976028,1.185964,0.049231,0.837983,16.976028
4,86.594742,0.020245,-0.022631,-0.002418,-24.092713,1.041627,-0.022631,0.941060,-24.092713
...,...,...,...,...,...,...,...,...,...
9995,-25.314857,-0.269162,0.089892,0.328029,-9.233893,2.474179,0.089892,0.557905,80.766107
9996,5.413002,-0.125716,0.018208,-0.024041,-4.120569,1.293563,0.018208,0.774579,85.879431
9997,54.291897,0.194503,-0.329392,-0.578496,-29.719237,4.132404,-0.329392,0.446621,-29.719237
9998,46.615898,0.000403,-0.055832,-0.007134,-44.793303,1.014394,-0.055832,0.894238,-44.793303
9999,-44.581551,-0.238290,0.130221,16.312635,-14.327910,-1.130596,0.130221,0.572883,75.672090